name: Manual Pytest Runner

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: SSH into VM and Run Pytest
        env:
          SSHPASS: ${{ secrets.SSH_PASSWORD }}
        run: |
          # Define variables
          REMOTE_USER="autotest"
          REMOTE_HOST="80.87.129.134"
          REMOTE_PORT="2250"
          REMOTE_DIR="/home/autotest/MERCER"

          # Execute commands on remote server using sshpass
          sshpass -e ssh -o StrictHostKeyChecking=no -p $REMOTE_PORT $REMOTE_USER@$REMOTE_HOST << EOF
            set -e  # Exit on error
            rm -rf $REMOTE_DIR/venv
            python3 -m venv $REMOTE_DIR/venv
            source $REMOTE_DIR/venv/bin/activate
            cd $REMOTE_DIR
            pip install -r requirements.txt  # Install dependencies
            pytest --html=report.html  # Run pytest
            cp report.html ../test-report/  # Copy report to test-report folder
          EOF
